apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-namespace-project1
  namespace: demo-acm-policies
placementRef:
  name: placement-policy-namespace-project1
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-namespace-project1
    kind: Policy
    apiGroup: policy.open-cluster-management.io
