---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: guestbook
  name: redis-slave-app-subscription-1
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: submariner/gb/redis-slave-app/redis-slave/
  labels:
    app: redis-slave-app
spec:
  channel: guestbook/redis-slave-app-latest
  placement:
    placementRef:
      name: redis-slave-app-placement-1
      kind: PlacementRule
