
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: guestbook-pr
  namespace: guestbook
  labels:
    app: guestbook-app
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      clusterid: cluster1
