apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: httpd     
  namespace: demo-acm
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - httpd 
  componentKinds:
  - group: apps.open-cluster-management.io/v1
    kind: Subscription
