apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: httpd                           
  namespace: demo-acm
  labels:
    app: httpd
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: 1/assets
spec:
  channel: demo-acm/git1
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster1only     
