apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpavm
spec:
  scaleTargetRef:
    kind: VirtualMachineInstanceReplicaSet
    name: vmirs-vm
    apiVersion: kubevirt.io/v1alpha3
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        periodSeconds: 15
        value: 10
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        periodSeconds: 15
        value: 10

