apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: vmirs-vm
spec:
  replicas: 2
  selector:
    matchLabels:
      myvmi: vm
  template:
    metadata:
      name: vm
      labels:
        myvmi: vm
    spec:
      domain:
        devices:
          disks:
          - disk:
            name: containerdisk
        resources:
          requests:
            memory: 256M
            cpu: 500m
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/apoczeka/vm:latest
