apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-consolelink
  namespace: demo-acm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: consolelink
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleLink
                metadata:
                  name: consolelink
                spec:
                  applicationMenu:
                    imageURL: https://upload.wikimedia.org/wikipedia/commons/2/24/Ansible_logo.svg
                    section: Red Hat Applications
                  href: https://www.ansible.com/
                  location: ApplicationMenu
                  text: Red Hat Automation Platform is cool!
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-consolelink
  namespace: demo-acm-policies
placementRef:
  name: placement-policy-consolelink
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-consolelink
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-consolelink
  namespace: demo-acm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []

